config/routes.rb
Rails.application.routes.draw do
  root 'events#index'
  get 'static_pages/index'
  get 'static_pages/secret'
  devise_for :users
  resources :events
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
    belongs_to :user
    belongs_to :event

    after_create :attendance_creation

    def attendance_creation
    AttendanceMailer.attendance_creation_email(self).deliver_now
  end
end

app/models/event.rb
class Event < ApplicationRecord
    has_many :attendances
    has_many :users, through: :attendances

    validates :start_date, :duration, :title, :description, :price, :location, presence: true

    validates :duration, numericality: { greater_than_or_equal_to: 5 }

    validates :title, length: { in: 5..140 }

    validates :description, length: { in: 20..1000 }

    validates :price, numericality: { greater_than: 0, less_than_or_equal_to: 1000}

    validate :start_date_after_current_date

    validate :duration_multiple

    private

    def start_date_after_current_date 
        if start_date < Date.current
          errors.add(:start_date, "Must be after current date")
        end
     end

     def duration_multiple
        if duration % 5 != 0
            errors.add(:duration, "Must be a multiple of 5")
        end
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :attendances
    has_many :events, through: :attendances

    after_create :welcome_send

    def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:show, :create]
  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
    #@attendance = Attendance.find(params[:id])
  end

  def create
    @event = Event.create(
      title: params[:event_title], 
      description: params[:event_description],
       price: params[:event_price], 
       start_date: params[:event_start_date], 
       duration: params[:event_duration], 
       location: params[:event_location] ) 
    if @event.save 
      flash[:success] = "L'évènement est bien crée ! "
      redirect_to root_path
     else
      render "new"
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!, only: [:secret]
  def index
  end

  def secret
    @user = current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
       @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<div class="jumbotron">
  <div class="container"style="text-align:center;">
    <h1 class="display-3">Les événements dans la ville Rôoooose !</h1>
    <p>Tu organises un nouvel évènement ? <br> Partage le à la communauté ! </p><a href="/events/new" class="btn btn-success btn-lg">Créer un évènement</a><br/>
  </div>
</div>
<% @events.each do |event|%>
<div class="card m-5 p-5" style="height:300px">
  <div class="card-body">
    <h3><%= event.title%></h3>
		<p><%= event.description%></p>
		<p><a href="<%= event_path(event.id)%>" class="btn btn-primary">Lire la suite</a></p>   
  </div>
</div>
<% end %>

app/views/events/new.html.erb
<div class="jumbotron1">
 <div class="container" style="text-align:center;">
   <h3 class="display-3">Créé un nouvel évènement</h3>
   <div id="new_event" class="card-body" >
<form action= "<%= events_path %>" method="POST">
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
 <div class="form-group">
   <label for="exampleInputEmail1">Titre de l'évènement</label>
   <input type="string" class="form-control" id="event_title" name="event_title" aria-describedby="title" placeholder="Choisissez un titre">
   <small id="emailHelp" class="form-text text-muted">Votre titre doit faire entre 5 et 140 caractères</small>
 </div>
 <div class="form-group">
   <label for="exampleInputEmail1">Prix de l'évènement</label>
   <input type="string" class="form-control" id="event_price" name="event_price" aria-describedby="prix" placeholder="Choisissez un prix">
   <small id="emailHelp" class="form-text text-muted">Votre prix doit faire entre 1 et 1000 euros</small>
 </div>
 <div class="form-group">
   <label for="content">Description de l'évènement</label>
   <textarea class="form-control" id="event_description" name="event_description" rows="4"></textarea>
   <small id="description" class="form-text text-muted">Votre description doit faire entre 20 et 1000 caractères</small>
 </div>
 <div class="row">
   <div class="col">
     <label for="col">Date et heure de l'évènement</label>
     <input type="text" id="event_start_date" name="event_start_date" class="form-control" placeholder="Au format YYYY-MM-DD HH:MM:SS">
   </div>
   <div class="col">
     <label for="col">Durée de l'évènement</label>
     <input type="text" id="event_duration" name="event_duration" class="form-control" placeholder="En minutes">
   </div>
   <div class="col">
     <label for="col">Lieu de l'évènement</label>
     <input type="text" id="event_location" name="event_location" class="form-control" >
   </div>
 </div>
 <br/><br/>
 <button type="submit" class="btn btn-primary">Envoyer</button>
</form>
   </div>
 </div>
</div>

app/views/events/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <br><br><br>
<div class="card text-center">
  <div class="card-header">
    <h3><%= @event.title %></h3>
  </div>
  <div class="card-body">
    
    <p class="card-text">Description : <%= @event.description %></p>
    <p class="card-text">Prix : <%= @event.price %></p>
    <p class="card-text">Date : <%= @event.start_date %></p>
    <p class="card-text">Durée : <%= @event.duration %> minutes</p>
    <p class="card-text">Lieu : <%= @event.location %></p>
    <br /><br />
    <a href="<%= root_path %>" class="btn btn-primary">Revenir aux évènements</a>
    <br /><br />
  </div>
  <div class="card-footer text-muted">
    Évènement créé le <%= @event.created_at %>
  </div>
</div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventbriteLike</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <title>Jumbotron Template for Bootstrap</title>
    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/jumbotron/">
    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="jumbotron.css" rel="stylesheet">
  </head>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">ToulouseBrite</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/">Accueil <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/events/new">Créer</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Ma session
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <ul>
  <% if user_signed_in? %>
    <li>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    </li>

    <li>
      Voici ton email : <%= current_user.email %>
    </li>

    <li>
      <%= link_to "Ton profil", static_pages_secret_path %>
    </li>

    <li>
      <%= link_to "Edit email / password", edit_user_registration_path %>
    </li>

  <% else %>
    <li>    
      <%= link_to "Sign in", new_user_session_path %>
    </li>

    <li>
      <%= link_to "Sign up", new_user_registration_path %>
    </li>

  <% end %>
</ul>

        </div>
      </li>
    </ul>
  </div>
</nav>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <%= yield %>
    
  </body>
</html>

app/views/static_pages/index.html.erb
<ul>
  <% if user_signed_in? %>
    <li>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    </li>

    <li>
      Voici ton email : <%= current_user.email %>
    </li>

    <li>
      <%= link_to "Secret page", static_pages_secret_path %>
    </li>

    <li>
      <%= link_to "Edit email / password", edit_user_registration_path %>
    </li>

  <% else %>
    <li>    
      <%= link_to "Sign in", new_user_session_path %>
    </li>

    <li>
      <%= link_to "Sign up", new_user_registration_path %>
    </li>

  <% end %>
</ul>

app/views/static_pages/secret.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <br><br><br>
<div class="card text-center">
  <div class="card-header">
  <h3>Ton profil</h3>
    
  </div>

  <div class="card-body">
  <h3><%= @user.email%></h3>
    <br />
    <a href="<%= root_path %>" class="btn btn-primary">Revenir aux évènements</a>
  </div>

  <div class="card-footer text-muted">
    Compte créé le <%= @user.created_at %>
  </div>
</div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <br><br><br>
<div class="card text-center">
  <div class="card-header">
    <h3><%= @user.first_name %> <%= @user.last_name %></h3>
  </div>

  <div class="card-body">
    <h5 class="card-title">Email : <%= @user.email %></h5>
    <p class="card-text"><%= @user.description %></p>
    <br /><br /><br />
    <a href="<%= root_path %>" class="btn btn-primary">Revenir aux évènements</a>
  </div>

  <div class="card-footer text-muted">
    Compte créé le <%= @user.created_at %>
  </div>
</div>
    </div>
  </div>
</div>